"""add form_answers cache table

Revision ID: 2b6d7d6684d4
Revises: 7e91e3bdf37a
Create Date: 2026-05-02 03:47:09.266091
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '2b6d7d6684d4'
down_revision: str | Sequence[str] | None = '7e91e3bdf37a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_norm', sa.String(length=200), nullable=False),
    sa.Column('question_raw', sa.String(length=500), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('answer', sa.String(length=2000), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.Column('last_company', sa.String(length=200), nullable=True),
    sa.Column('last_job_title', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_norm', name='uq_form_answers_qnorm')
    )
    with op.batch_alter_table('form_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_form_answers_question_norm'), ['question_norm'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_form_answers_question_norm'))

    op.drop_table('form_answers')
    # ### end Alembic commands ###
