"""initial schema

Revision ID: 7e91e3bdf37a
Revises:
Create Date: 2026-05-01 23:35:31.296089
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "7e91e3bdf37a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("tech_stack", sa.String(length=500), nullable=True),
        sa.Column("headcount", sa.Integer(), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("is_hiring", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("last_dm_scan_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_companies_name"), ["name"], unique=True)

    op.create_table(
        "decision_makers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("title_raw", sa.String(length=300), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column("contacts", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "full_name", name="uq_dm_company_name"),
    )
    with op.batch_alter_table("decision_makers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_decision_makers_company_id"), ["company_id"], unique=False
        )

    op.create_table(
        "job_postings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.String(length=5000), nullable=True),
        sa.Column("tech_stack", sa.String(length=500), nullable=True),
        sa.Column("seniority", sa.String(length=30), nullable=True),
        sa.Column("is_remote", sa.Boolean(), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("salary_min", sa.Integer(), nullable=True),
        sa.Column("salary_max", sa.Integer(), nullable=True),
        sa.Column("salary_currency", sa.String(length=10), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("applicants_count", sa.Integer(), nullable=True),
        sa.Column("posted_at", sa.DateTime(), nullable=True),
        sa.Column("apply_email", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_url", name="uq_jp_source_url"),
    )
    with op.batch_alter_table("job_postings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_job_postings_company_id"), ["company_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_job_postings_source_url"), ["source_url"], unique=False
        )

    op.create_table(
        "applies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_posting_id", sa.Uuid(), nullable=True),
        sa.Column("decision_maker_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("flank", sa.String(length=20), nullable=False),
        sa.Column("method", sa.String(length=20), nullable=False),
        sa.Column("channel", sa.String(length=30), nullable=True),
        sa.Column("relevance_score", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=True),
        sa.Column("body", sa.String(length=4000), nullable=True),
        sa.Column("cover_letter", sa.String(length=4000), nullable=True),
        sa.Column("form_responses", sa.JSON(), nullable=True),
        sa.Column("apply_url", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.String(length=2000), nullable=False),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("response_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["decision_maker_id"],
            ["decision_makers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_posting_id"],
            ["job_postings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "job_posting_id", "decision_maker_id", "attempt_no", name="uq_apply_job_dm_attempt"
        ),
    )
    with op.batch_alter_table("applies", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_applies_decision_maker_id"), ["decision_maker_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_applies_job_posting_id"), ["job_posting_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("applies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_applies_job_posting_id"))
        batch_op.drop_index(batch_op.f("ix_applies_decision_maker_id"))

    op.drop_table("applies")
    with op.batch_alter_table("job_postings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_postings_source_url"))
        batch_op.drop_index(batch_op.f("ix_job_postings_company_id"))

    op.drop_table("job_postings")
    with op.batch_alter_table("decision_makers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_decision_makers_company_id"))

    op.drop_table("decision_makers")
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_companies_name"))

    op.drop_table("companies")
    # ### end Alembic commands ###
